version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres

postgres:
  build: 
    context: .
    dockerfile: dockerfile-postgres
  ports:
    - "5432:5432"